### ISSUE TITLE
Small change to the Makefile is needed for the code to compile on GNU/Linux

### ISSUE THREAD

**Issue by vlad-bulakh** [minirop/Super-Mario-Remake#1]
I was unable to compile the code on GNU/Linux.  Changing the following line in the Makefile:
"LIBSU=-lSDLmain -lSDL.dll -lSDL_image"
to:
"LIBSU=-lSDLmain -lSDL -lSDL_image"
allowed the code to compile.

**Comment by minirop** [comment]
thanks. but don't lose to much time on this "thing". it's not like it's something playable. ^^
